clusterlink-net/clusterlink

dockerfile, pkg/controlplane/api/heartbeat.go, pkg/controlplane/client.go, pkg/controlplane/instance.go, pkg/controlplane/server/http/heartbeat.go, pkg/controlplane/server/http/server.go
Add heartbeat mechanism to new controlplane for checking liveness between peers
Signed-off-by: Kfir Toledo <kfir.toledo@ibm.com>
=> [New]: Add heartbeat for the new controlplane

tests/k8s.sh
This should fix the failing e2e tests in the CI.
=> tests/k8s.sh: Move iperf server to a new pod

pkg/platform/k8s/pod_reconciler.go
This PR adds a lock for accessing the maps in PodReconciler, which can be accessed from multiple threads.
Fixes: #124.
=> pkg/platform/k8s: Add locking to multi-threaded maps

cmd/gwctl/subcommand/export.go, pkg/controlplane/authz.go
This PR fixes the security warnings reported by CodeQL.
=> Fix CodeQL security warnings.

demos/qotd/kind/test.py
Update for QotD application demo.
=> demos/qotd: Update for QotD application demo

pkg/dataplane/client/xds.go
This PR reduces the xDS client connect timeout from the default 20 seconds to 1 second.
Fixes: #141.
=> dataplane: Reduce xDS client connect timeout

pkg/controlplane/authz.go
Add source service to a connection request to the policy engine.
=> controlplane/authz: Add source service to a connection request to the policy engine

.devcontainer/devcontainer.json, .gitignore, .licenserc.yaml, Containerfile.dev, Makefile, hack/install-devtools.sh
Changed Makefile targets and added script to install dev tools
Signed-off-by: Etai Lev Ran <elevran@gmail.com>
=> Support for dev-container

cmd/cl-adm/cmd/create/create_peer.go, pkg/bootstrap/platform/config.go, pkg/bootstrap/platform/k8s.go, tests/e2e/k8s/util/k8s_yaml.go
Add log-level flag to control the level of log messages.
=> cmd/cl-adm: Add log-level flag

CONTRIBUTING.md, README.md
Fixes #50 
Need to make a separate decision (and follow up PR) regarding maintainers and governance files (see #51 for sample contents).
=> Review and amend open source files

pkg/controlplane/server/http/api.go
Fix the get list() return value for peer, export and import.
=> controlplane/server: Fix list() return value

website/assets/icons/logo.svg, website/hugo.toml
- include a search box (offline search)
- avoid translucency on landing page (cover shortcode)
=> Tweak the top navbar

.golangci.yaml, pkg/controlplane/instance.go, pkg/controlplane/server/http/api.go, pkg/dataplane/server/forwarder.go, pkg/platform/k8s/platform.go, pkg/policyengine/connectivitypdp/connectivity_pdp_test.go, pkg/store/kv/store.go, pkg/util/rest/server.go
Signed-off-by: MICHAL MALKA <Michal.Malka@ibm.com>
=> Fix linter errors on existing code

website/content/en/docs/doc-contribution/_index.md
=> Sample edit

.golangci.yaml, pkg/k8s/kubernetes/kubeinformer.go, pkg/platform/k8s/reconciler.go
Replaces previous PR #250.
- simplify owner-ref logic, align happy path to left
- simplify reconcile logic, align happy path to left
- enable nestif linter in configuration
Reference #61
=> Enable `nestif` linter

.golangci.yaml, cmd/gwctl/config/config.go, cmd/gwctl/subcommand/gwctl.go, cmd/gwctl/subcommand/metrics.go, pkg/k8s/kubernetes/kubeinformer.go, pkg/metrics/metrics.go, pkg/platform/k8s/pod_reconciler.go, pkg/policyengine/PolicyDispatcher.go, pkg/policyengine/connectivitypdp/connectivity_pdp.go, pkg/policyengine/connectivitypdp/connectivity_pdp_test.go
- hugeParam: pass by pointer, not by value
- rangeValCopy: use index to collection instead of value copy in iteration
References #61
=> Enabled additional `gocritic` checks

.golangci.yaml, cmd/cl-controlplane/app/server.go, pkg/controlplane/client.go, pkg/controlplane/instance.go, pkg/controlplane/server/http/api.go, pkg/dataplane/client/fetcher.go, pkg/dataplane/server/dataplane.go, pkg/dataplane/server/forwarder.go, pkg/dataplane/server/listener.go, pkg/dataplane/server/server.go, pkg/k8s/kubernetes/kubeinformer.go, pkg/platform/k8s/platform.go, pkg/platform/k8s/pod_reconciler.go, pkg/platform/k8s/pod_reconciler_test.go, pkg/policyengine/loadBalancer.go, pkg/store/kv/manager.go, pkg/store/kv/store.go, pkg/util/log/log.go, pkg/utils/netutils/netutils.go, tests/e2e/k8s/util/clusterlink.go, tests/e2e/k8s/util/kind.go
=> changes for gocritic linter

.golangci.yaml, cmd/cl-dataplane/app/server.go, cmd/gwctl/config/config.go, cmd/gwctl/subcommand/export.go, cmd/gwctl/subcommand/import.go, cmd/gwctl/subcommand/peer.go, cmd/gwctl/subcommand/policy.go, pkg/controlplane/client.go, pkg/controlplane/xdsmanager.go, pkg/dataplane/client/xds.go, pkg/dataplane/server/dataplane.go, pkg/policyengine/policytypes/connectivity_policy_test.go, pkg/util/log/log.go, pkg/util/rest/server.go, pkg/util/sniproxy/server.go, tests/e2e/k8s/test_basic.go, tests/e2e/k8s/util/fabric.go
=> variable name length linting fixes

config/operator/crds/clusterlink.net_instances.yaml, config/operator/manager/manager.yaml, config/operator/rbac/leader_election_role.yaml, config/operator/rbac/leader_election_role_binding.yaml, config/operator/rbac/operator_editor_role.yaml, config/operator/rbac/operator_viewer_role.yaml, config/operator/rbac/role_binding.yaml, config/operator/rbac/service_account.yaml
Add operator deployment(manager) and rbacs.
Note: All the config files were generated by the Kubebuildrer CLI.
References #286
=> config/operator: Add operator YAMLs

Makefile, cmd/cl-operator/Dockerfile, cmd/cl-operator/main.go, go.mod, go.sum, pkg/operator/controller/instance_controller.go
The deployment operator creates an operator to deploy ClusterLink. 
Its main component is the instance_controller, which takes the ClusterLink instance CRD and creates the ClusterLink components
References #286 
**Note: This code depends on PR https://github.com/clusterlink-net/clusterlink/pull/259**
=> cmd/cl-operator: Introduce the deployment operator (cl-operator).

Makefile, hack/install-devtools.sh
This PR adds gofumpt to the format target.
=> Makefile: Add gofumpt

cmd/cl-dataplane/app/envoy.go, cmd/cl-dataplane/app/envoyconf.go, pkg/controlplane/api/authz.go, pkg/controlplane/api/xds.go, pkg/controlplane/authz.go, pkg/controlplane/server/http/authz.go, pkg/controlplane/xdsmanager.go, pkg/dataplane/server/listener.go, pkg/policyengine/policytypes/connection_request.go
This PR changes the xDS and authz protocols to support namespaced imports/exports.
=> Prepare for import/export namespace support

cmd/cl-operator/main.go, config/operator/crds/clusterlink.net_instances.yaml, pkg/apis/clusterlink.net/v1alpha1/instance_types.go, pkg/operator/controller/instance_controller.go
Small fixes:
1. Handle more than one instance in the same namespace 
2. Fix IngressName to cl-ingress
=> operator/controller: Handle more than one instance in the same namespace 

cmd/cl-adm/cmd/create/create_peer.go, pkg/bootstrap/platform/k8s.go, pkg/operator/controller/instance_controller.go, tests/e2e/k8s/suite.go, tests/e2e/k8s/util/fabric.go, tests/e2e/k8s/util/k8s_yaml.go, tests/e2e/k8s/util/kind.go
Add options to create Clustrlink using the operator in the e2e tests.
=> tests/e2e: Add support to create cluster with operator

tests/e2e/k8s/test_operator.go, tests/e2e/k8s/util/fabric.go, tests/e2e/k8s/util/kind.go
Add a new e2e test for checking operator deployment.
=> tests/e2e: Introduce new e2e operator test

cmd/cl-controlplane/app/server.go, pkg/controlplane/instance.go, pkg/controlplane/xds/manager.go, pkg/controlplane/xds/server.go
This PR moves the xDS manager to the xds package, and change it to the new API objects.
=> controlplane/xds: Introduce Manager

.devcontainer/dev/post-create.sh, Makefile, hack/install-devtools.sh, pkg/operator/controller/instance_controller.go, pkg/operator/controller/instance_controller_test.go
Adding deployment operator unit test using envtests environment.
Signed-off-by: Kfir Toledo <kfir.toledo@ibm.com>
=> operator/controller: Add controller unit test

tests/e2e/k8s/test_operator.go
Add a wait condition to check component creation in the operator test.
=> tests/e2e: Add wait condition to operator test

website/content/en/_index.md, website/content/en/docs/reference/_index.md
replaces #353 which became a history merge chaos...
=> replaced references with overview section

pkg/controlplane/control/manager.go, pkg/controlplane/control/port.go, pkg/controlplane/rest/import.go
This PR fixes the previously broken port deletion.
=> controlplane/control: Delete ports by name

Makefile
Remove unused targets in the Makefile.
=> Makefile: Remove unused targets

cmd/cl-adm/cmd/create/create_peer.go, cmd/cl-adm/cmd/deploy/deploy_peer.go, cmd/cl-adm/config/config.go, config/operator/manager/manager.yaml
Support container registry flag in deploy peer command.
=> cmd/deploy: Support container registry flag in deploy peer command.

cmd/gwctl/subcommand/export.go, pkg/api/types.go, pkg/client/client.go, pkg/controlplane/rest/export.go, pkg/controlplane/store/types.go, pkg/policyengine/PolicyDispatcher.go, tests/e2e/k8s/test_basic.go, tests/e2e/k8s/test_operator.go, tests/e2e/k8s/test_performance.go, tests/e2e/k8s/util/clusterlink.go
This PR moves all uses of api.Export to v1alpha1.Export.
=> pkg/api: Switch to v1alpha1.Export

cmd/gwctl/subcommand/peer.go, pkg/api/types.go, pkg/client/client.go, pkg/controlplane/rest/peer.go, pkg/controlplane/store/types.go, tests/e2e/k8s/test_basic.go, tests/e2e/k8s/util/clusterlink.go
This PR moves all uses of api.Peer to v1alpha1.Peer.
=> pkg/api: Switch to v1alpha1.Peer

cmd/gwctl/subcommand/import.go, pkg/api/types.go, pkg/client/client.go, pkg/controlplane/authz/manager.go, pkg/controlplane/rest/import.go, pkg/controlplane/store/types.go, pkg/policyengine/PolicyDispatcher.go, pkg/policyengine/PolicyDispatcher_test.go, tests/e2e/k8s/test_basic.go, tests/e2e/k8s/util/clusterlink.go
This PR moves all uses of api.Import to v1alpha1.Import.
=> pkg/api: Switch to v1alpha1.Import

website/content/en/docs/getting-started/_index.md, website/content/en/docs/getting-started/developers.md, website/content/en/docs/overview/_index.md
=> Complete draft of developer getting started guide

GOVERNANCE.md
=> Complete governance document

cmd/gwctl/subcommand/policy.go, config/crds/clusterlink.net_imports.yaml, demos/bookinfo/cloud/apply_lb.py, demos/bookinfo/kind/README.md, demos/bookinfo/kind/apply_lb.py, demos/bookinfo/test.py, pkg/apis/clusterlink.net/v1alpha1/import.go, pkg/policyengine/loadBalancer.go, pkg/policyengine/loadBalancer_test.go
Set ECMP as the default LBScheme for import
=> v1alpha1/import: Set Round-Robin as the default LBScheme

pkg/operator/controller/instance_controller.go, tests/e2e/k8s/test_operator.go
Update the operator to support only CRD mode
=> operator/controller: Update the operator to support only CRD mode

tests/e2e/k8s/test_basic.go, tests/e2e/k8s/test_operator.go, tests/e2e/k8s/test_performance.go, tests/e2e/k8s/util/fabric.go, tests/e2e/k8s/util/k8s_yaml.go
This PR switches the default mode to CRD-mode.
=> tests/e2e/k8s: Set CRD mode as default

Makefile
Change ENVTEST_VERSION from "latest" to "395cfc7"
=> Makefile: Change ENVTEST_VERSION

go.mod, go.sum, pkg/util/sniproxy/server.go
no longer able to build fresh copy locally as the original inet.af domain was removed and packages moved
=> inet.af was hijacked and repo moved to github

website/config.toml
`disable` replaced by `enable`
=> [website] latest docsy changes default ui param

pkg/controlplane/control/manager.go
Discovered by upcoming e2e tests (to be added soon).
=> controlplane/control: Bug fixes

pkg/controlplane/control/peer.go
This PR fixes the case where a peer monitor is updated.
Previously, the old monitor was not stopped.
Furthermore, the monitor always assumed the peer status is not set to reachable, which is not always the case.
=> controlplane/control: Fix updating of peer monitor

pkg/controlplane/control/manager.go, tests/e2e/k8s/test_export.go, tests/e2e/k8s/test_import.go, tests/e2e/k8s/test_peer.go, tests/e2e/k8s/util/clusterlink.go, tests/e2e/k8s/util/kind.go
This PRadds further e2e tests testing the CRD-based controlplane.
It mostly tests the control component of the controlplane.
=> tests/e2e/k8s: Add more CRD-mode tests

README.md, demos/iperf3/testdata/manifests/clusterlink/allow-policy.yaml, demos/iperf3/testdata/manifests/clusterlink/export-iperf3.yaml, demos/iperf3/testdata/manifests/clusterlink/import-iperf3.yaml, demos/iperf3/testdata/manifests/clusterlink/peer-client.yaml, demos/iperf3/testdata/manifests/clusterlink/peer-server.yaml, website/content/en/docs/tutorials/iperf.md
Add iperf3 tutorials to documentation.
=> website: Add iPerf3 tutorial

website/content/en/docs/concepts/fabric.md, website/content/en/docs/concepts/peers.md, website/content/en/docs/concepts/policies.md, website/content/en/docs/concepts/services.md
=> [website] Service sharing concept documentation

website/content/en/docs/tutorials/iperf.md
Small fix for URL path to work with environment variable.
=> tutorials/iperf3: Fix URLpath.

.github/release.yml
Add automatically generated release notes yaml.
=> .github/release: Add automatically generated release notes yaml

.devcontainer/dev/post-create.sh, .github/workflows/pr-check.yml, .github/workflows/pr-e2e-test.yml, Containerfile.dev, Makefile, README.md, config/crds/clusterlink.net_accesspolicies.yaml, config/crds/clusterlink.net_exports.yaml, config/crds/clusterlink.net_imports.yaml, config/crds/clusterlink.net_instances.yaml, config/crds/clusterlink.net_peers.yaml, config/crds/clusterlink.net_privilegedaccesspolicies.yaml, go.mod, go.sum
Update Go toolchain to use 1.22 and later.
Fixes #478
=> [Feature]: go1.22 support

website/content/en/docs/getting-started/users.md
Update the uninstall section for ClusterLink CLI
=> docs/getting-started: update the uninstall section

website/content/en/about/_index.md, website/content/en/docs/_index.md, website/content/en/docs/concepts/fabric.md, website/content/en/docs/concepts/peers.md, website/content/en/docs/concepts/policies.md, website/content/en/docs/concepts/services.md, website/content/en/docs/getting-started/developers.md, website/content/en/docs/getting-started/users.md, website/content/en/docs/tutorials/iperf.md
=> [website] Minor indentation and wording changes

website/content/en/docs/concepts/peers.md, website/content/en/docs/concepts/policies.md, website/content/en/docs/concepts/services.md, website/content/en/docs/getting-started/users.md, website/static/files/peer_crd_sample.yaml
1) Update the peer deploy command.
2) Add command outputs and CR example to the peer concept.
3) Update YAMLs examples to the service concept.
https://deploy-preview-505--clusterlink-net.netlify.app/
=> website/content: update Concepts' YAML files

website/content/en/docs/tasks/operator.md
Add manual deployment without using the CLI.
=> website: Add manual deployment section

cmd/clusterlink/cmd/create/create_peer.go, cmd/clusterlink/cmd/delete/delete_peer.go, cmd/clusterlink/cmd/deploy/deploy_peer.go, demos/utils/cloud.py, demos/utils/clusterlink.py, demos/utils/kind.py, pkg/bootstrap/cert.go, website/content/en/docs/main/concepts/peers.md, website/content/en/docs/main/getting-started/users.md, website/content/en/docs/main/tasks/operator.md, website/content/en/docs/main/tutorials/iperf.md
1) Move file creations to deploy command.
2) Add a dry-run flag.
=> cmd/clusterlink: Move file creation to deploy command

hack/gen-doc-version.sh
=> [website] Update markdown to use GIT tag param in release links

website/content/en/docs/main/getting-started/users.md, website/content/en/docs/v0.1/getting-started/users.md, website/content/en/docs/v0.2/getting-started/users.md
Fix the tutorials link in the User guide,
=> website: Fix tutorials link in User guide

website/content/en/docs/main/getting-started/users.md
Explain in more detail to use the same fabric files for peers in the same fabric.
=> website: Refining the explanation for how to create certificates

website/content/en/docs/main/doc-contribution/_index.md, website/content/en/docs/main/getting-started/_index.md, website/content/en/docs/main/overview/_index.md, website/content/en/docs/main/tasks/operator.md, website/content/en/docs/main/tutorials/bookinfo/index.md, website/content/en/docs/main/tutorials/iperf/index.md, website/content/en/docs/v0.1/doc-contribution/_index.md, website/content/en/docs/v0.1/getting-started/_index.md, website/content/en/docs/v0.1/overview/_index.md, website/content/en/docs/v0.1/tutorials/iperf.md, website/content/en/docs/v0.2/doc-contribution/_index.md, website/content/en/docs/v0.2/getting-started/_index.md, website/content/en/docs/v0.2/overview/_index.md, website/content/en/docs/v0.2/tasks/operator.md, website/content/en/docs/v0.2/tutorials/bookinfo/index.md, website/content/en/docs/v0.2/tutorials/iperf.md, website/netlify.toml
Consistently use "relref" instead of "naked" links
=> [website] Replace relative link with relref

website/content/en/docs/main/concepts/_index.md, website/content/en/docs/main/concepts/fabric.md, website/content/en/docs/main/concepts/peers.md, website/content/en/docs/main/getting-started/developers.md
Replaces #571 #570 #569 #568 from @welisheva
=> [website] minor edits

website/content/en/about/_index.md
=> [website] revise About page based on intro blog

.github/workflows/release.yml, hack/install_clusterlink.sh, website/content/en/docs/main/getting-started/users.md
Add instructions for installation for the specific version.
=> website: Add description for CLI version

pkg/controlplane/control/peer.go
Add logs to controlplane when a heartbeat is fail
=> controlplane: Add error message when hearbeat fail.

cmd/cl-controlplane/app/server.go, config/operator/rbac/role.yaml, pkg/bootstrap/platform/k8s.go, pkg/controlplane/control/controllers.go, pkg/operator/controller/instance_controller.go, pkg/util/controller/controller.go
This PR adds leader election for control controllers.
=> controlplane: Use leader election for control controllers

tests/e2e/k8s/test_operator.go
This PR fixes TestOperator which was broken by the last merged PR.
=> tests/e2e/k8s: Fix TestOperator

pkg/operator/controller/instance_controller.go, pkg/operator/controller/instance_controller_test.go
Fix the name of clusterrole and clusterrolebindings (same name for deletion and creation).
=> operator: Fix delete ClusterRule name
