- cmd/gwctl/main.go
- cmd/gwctl/subcommand/gwctl.go
Add get all commands that prints all: peers, imports, exports, bindings and policies.
> cmd/gwctl: Add get all command

- tests/k8s.sh
This PR fixes the iperf server setup.
> tests/k8s.sh: Fix iperf server setup

- .golangci.yaml
- Makefile
- pkg/controlplane/store/store.go
- pkg/k8s/kubernetes/kubeinformer.go
- pkg/metrics/metrics.go
- pkg/policyengine/accessControl.go
- pkg/util/jsonapi/client.go
This PR enables additional linters. The list represents (what I think is) a reasonable set of linters that should be run in CICD.
However, some linters are currently disabled in the `golangci.yaml` configuration as the existing code does not pass the checks.
Future PRs can update the linter set or their configuration by removing the commented out lines and setting `issues.new: false` in `golangci.yaml`  and then running `make lint` and fixing any reported issues. This work will tracked in a #61.
> cicd: Enable additional linters

- cmd/gwctl/subcommand/policy.go
- pkg/client/client.go
- pkg/controlplane/authz.go
- pkg/controlplane/instance.go
- pkg/controlplane/server/http/api.go
- pkg/controlplane/store/accesspolicies.go
- pkg/controlplane/store/types.go
- pkg/policyengine/PolicyDispatcher.go
- pkg/policyengine/PolicyDispatcher_test.go
- pkg/policyengine/loadBalancer.go
- tests/k8s.sh
Includes:
* API calls to CRUD access policies
* Calling policy engine to authorize outgoing/incoming connections
* Policy engine sets remote peer for outgoing connections
* Calling policy engine to authorize adding bindings and exports
* Informing policy engine of added/removed peers and removed bindings and exports
* Persistent storage of access policies
Does not include:
* Handling load-balancing policies
> Policy engine integration with new cp

- .github/workflows/pr-e2e-test.yml
Adding timeout to github actions for the e2e-tests
> .github/workflows: add timeout to e2e tests

- Makefile
- tests/e2e/connectivity/basic_test.go
- tests/e2e/iperf3/iperf3_test.go
- tests/e2e/utils/common.go
- tests/e2e/utils/kind.go
Allow to run the iperf3 test and e2e connectivity test with the new controlplane.
> tests/iperf3 : support new control plane for k8s tests

- Makefile
Currently, when running `make copr-fix` I get (on both Ubuntu and Windows):
```
$ make copr-fix
adding copyright header...
docker run -it --rm -v :/github/workspace apache/skywalking-eyes header fix
docker: invalid spec: :/github/workspace: empty section between colons.
See 'docker run --help'.
make: *** [Makefile:48: copr-fix] Error 125
```
Seems like `$(pwd)` is not good enough on some environments.
Many suggest to replace it with `$(shell pwd)`
> Fix failing volume mount in "make copr-fix"

- cmd/cl-adm/templates/config.go
This PR fixes a recent bug in cl-adm which disallows the use of envoy dataplane.
> cmd/cl-adm: Fix bug that disables envoy use

- .golangci.yaml
- cmd/cl-adm/cmd/create/create_peer.go
- cmd/cl-adm/templates/docker.go
- cmd/cl-adm/templates/k8s.go
- cmd/cl-dataplane/app/envoy.go
- cmd/cl-dataplane/app/server.go
- cmd/cl-go-dataplane/app/server.go
- cmd/gwctl/subcommand/gwctl.go
- pkg/controlplane/authz.go
- pkg/controlplane/client.go
- pkg/controlplane/instance.go
- pkg/controlplane/server/controller.go
- pkg/controlplane/server/http/api.go
- pkg/dataplane/client/xds.go
- pkg/dataplane/server/server.go
- pkg/store/kv/bolt/store.go
- pkg/store/kv/store.go
- pkg/util/jsonapi/client.go
- pkg/util/log/log.go
- pkg/util/rest/client.go
- pkg/util/tls.go
- tests/e2e/utils/kind.go
- tests/k8s.sh
This PR changes wrapped errors to use %w instead of %v.
> Wrap errors correctly

- CONTRIBUTING.md
Considerably shortened version of the contribution guide, based on feedback in #87.
Fixes #82.
> Simpler and shorter Contribution Guide

- go.mod
- go.sum
- pkg/platform/k8s/platform.go
This PR enables k8s controller-runtime logging.
Fixes: #140.
> platform/k8s: Enable controller-runtime logging

- pkg/util/sniproxy/server.go
This PR reduces the dial timeout of the SNI proxy from 10 seconds to 100ms.
Fixes: #144.
> util/sniproxy: Reduce dial timeout

- pkg/dataplane/server/server.go
This PR fixes the dataplane-to-dataplane connection establishment to verify that the remote peer actually returned HTTP 200.
Fixes: #154
> dataplane/server: Fix HTTP status check

- cmd/cl-dataplane/app/envoyconf.go
- pkg/controlplane/api/authz.go
This PR changes the client IP header from x-forwarded-to to x-client-ip. This is to avoid a collision with envoy ext_authz client which overrides this header.
> controlplane/api/authz: Change client IP header

- cmd/cl-adm/cmd/create/create_peer.go
- pkg/bootstrap/platform/config.go
- pkg/bootstrap/platform/k8s.go
- tests/e2e/k8s/util/k8s_yaml.go
Add a remote-image flag that chooses whether to use a local or remote image. 
Add a container-registry flag that represents the container registry to pull the project images.
Signed-off-by: Kfir Toledo <kfir.toledo@ibm.com>
> cmd/cl-adm: Add container registry flag

- pkg/dataplane/server/listener.go
This PR closes a failed connection socket, instead of keeping it hanging.
Fixes: #174.
> dataplane/server/listener: Close socket on error

- pkg/controlplane/authz.go
- pkg/controlplane/client.go
- pkg/controlplane/instance.go
Update peer status in policy-engine according to the heartbeat status.
> controlplane: connect enable/disable peer to heartbeat

- tests/e2e/k8s/util/clusterlink.go
This PR fixes the function that waits for the controlplane server to come up, to allow timeout errors. This should resolve CI errors that mention: context deadline exceeded (Client.Timeout exceeded while awaiting headers).
e.g. https://github.com/clusterlink-net/clusterlink/actions/runs/6839437393/job/18597588234
> tests/e2e/k8s: Allow timeout errors

- .gitignore
- Makefile
- hack/install-devtools.sh
- Ensure installed tools are added to the PATH (source instead of run tooling)
- move empty target files under `dist`
- adding missing info messages in Makefile
> Devcontainer fixes

- cmd/cl-dataplane/app/envoyconf.go
Increasing Envoy's max_outbound_frames to support high throughput traffic.
> cmd/cl-dataplane: Increasing Envoy's max_outbound_frames

- pkg/controlplane/instance.go
- pkg/controlplane/server/http/api.go
- pkg/util/rest/server.go
This PR fixes the GET API for import/export/peer to return 404
when the requested object does not exist.
Previously, an empty 200 was returned.
This PR also fixes some wrong log message.
> controlplane: Return 404 on object not found

- cmd/gwctl/subcommand/policy.go
- pkg/controlplane/instance.go
- pkg/controlplane/server/http/api.go
This PR changes the API for deleting policies (both access and LB). Instead of deleting by value, delete by name.
> controlplane: Make policies deletable by name

- pkg/controlplane/instance.go
- pkg/policyengine/PolicyDispatcher.go
- pkg/policyengine/PolicyDispatcher_test.go
This {R changes the policy dispatcher to avoid deletion of bindings relevant to a deleted peer.
The peer is still removed from the enabled peers list.
This allows for re-creating a deleted peer without re-creating the relevant bindings.
> policyengine: Don't remove bindings of a deleted peer

- pkg/controlplane/server/http/api.go
This change was forgotten in #213
> controlplane: Return 404 on bindings not found

- pkg/dataplane/server/server.go
This PR changes the ingress setup connection to ACK (via connection hijacking) only after it was able to successfully dial to the target service.
> pkg/dataplane/server: Change ingress connection setup order

- tests/e2e/k8s/services/errors.go
- tests/e2e/k8s/services/httpecho/client.go
- tests/e2e/k8s/services/httpecho/server.go
- tests/e2e/k8s/services/iperf3/client.go
- tests/e2e/k8s/services/iperf3/server.go
- tests/e2e/k8s/suite.go
- tests/e2e/k8s/test_basic.go
- tests/e2e/k8s/test_performance.go
- tests/e2e/k8s/util/clusterlink.go
- tests/e2e/k8s/util/fabric.go
- tests/e2e/k8s/util/k8s_yaml.go
- tests/e2e/k8s/util/kind.go
This PRadds an e2e test which verifies the controlplane CRUD API.
It also includes some refactoring and tweaking of the e2e/k8s suite.
The changes in high-level:
1. Move services out from the suite to a new sub-package.
2. Test service access using nodeport exposing, instead of API server proxy.
3. Let k8s choose the nodeports used by the dataplane services.
4. Get rid of API server raw client. Use clientset for fetching pod logs instead.
5. Add test API which allows stop/start/restart of controlplane/dataplane.
> tests/e2e/k8s: Add controlplane CRUD test

- pkg/dataplane/server/server.go
This PR adds a 1 second timeout for dialing to an exported service.
> dataplane/server: Add timeout for service dialing

- tests/e2e/k8s/util/kind.go
Kind cluster creation can fail due to a race between parallel cluster creations conflicting on API server listening port on host machine. This PR adds a retry for cluster creation to avoid these type of errors.
> tests/e2e/k8s: Retry cluster creation

- .github/workflows/pr-e2e-test.yml
- pkg/controlplane/instance.go
- pkg/dataplane/server/forwarder.go
- pkg/util/jsonapi/client.go
- tests/e2e/k8s/services/httpecho/client.go
Mainly, adding a retry for the HTTP client using a fresh (non re-used) connection.
> Various nit fixes

- website/i18n/en.toml
Replace the default search placeholder (`Search this site...`) with an empty string so only magnifying glass shows
> Set search placeholder (for en)

- .golangci.yaml
- cmd/gwctl/subcommand/gwctl.go
- pkg/k8s/kubernetes/kubeinformer.go
- pkg/platform/k8s/pod_reconciler_test.go
- pkg/utils/netutils/netutils.go
- add to configured linters
- remove empty lines reported
> enable whitespace linter

- .golangci.yaml
- pkg/platform/k8s/platform.go
- pkg/platform/k8s/pod_reconciler.go
- pkg/platform/k8s/pod_reconciler_test.go
- tests/e2e/k8s/k8s_test.go
- enable linter in configuration
- move tests to their own package
- change tests to only inspect external behavior (e.g., no labels returned for deleted Pod, not that arrays are empty)
> make `testpackage` linter pass

- .golangci.yaml
- pkg/policyengine/PolicyDispatcher_test.go
- pkg/policyengine/loadBalancer_test.go
- enable thelper in configuration
- call t.Helper() in helper functions so correct test case is printed
> Enable `thelper` linter

- .golangci.yaml
- cmd/gwctl/config/config.go
- cmd/gwctl/subcommand/config.go
- pkg/controlplane/store/accesspolicies.go
- pkg/controlplane/store/bindings.go
- pkg/controlplane/store/exports.go
- pkg/controlplane/store/imports.go
- pkg/controlplane/store/lbpolicies.go
- pkg/controlplane/store/peers.go
- pkg/k8s/kubernetes/kubeinformer.go
- pkg/policyengine/connectivitypdp/connectivity_pdp.go
- pkg/util/log/log.go
- pkg/versioninfo/version.go
- tests/e2e/k8s/util/kind.go
- enable options
- fix unchecked errors
- fix unchecked type assertions
- left some as-is (with `//nolint:errcheck` comment)
> Enable additional errcheck linter options

- Makefile
Before this PR, I was not able to run `make prereqs`:
```
oro@oro:~/go/src/github.com/clusterlink-net/clusterlink$ make prereqs
installing dev tooling...
make: source: No such file or directory
make: *** [Makefile:24: prereqs] Error 127
```
See here also:
https://stackoverflow.com/questions/44052093/makefile-with-source-get-error-no-such-file-or-directory
> Makefile: don't use source command

- cmd/cl-adm/cmd/create/create_peer.go
- cmd/cl-adm/config/config.go
- pkg/bootstrap/platform/k8s.go
Add support to:
1. Create `cl-secret.yaml` that contains all the certificates for the controlplane and dataplane. 
2. Create `cl-instance.yaml` that use to deploy the ClusterLink project via the operator.
> cmd/cl-adm: Introduce `cl-secret.yaml` and `cl-instance.yaml`

- Makefile
- config/operator/crds/clusterlink.net_instances.yaml
- config/operator/rbac/role.yaml
- hack/boilerplate.go.txt
Add controller-gen target, codegen target and its outputs:
1. `clusterlink.net_operators.yaml` - The CRD yaml used by the operator.
2. `rbac/role.yaml` - The RBACs for the operator.
> Makefile: Add codegen target

- cmd/cl-adm/cmd/create/create_peer.go
- cmd/cl-controlplane/app/server.go
- pkg/bootstrap/platform/config.go
- pkg/bootstrap/platform/k8s.go
- tests/e2e/k8s/util/k8s_yaml.go
This PR adds a new controlplane flag for enabling the new CRD-based mode.
> controlplane: Add CRD mode flag

- cmd/cl-adm/cmd/create/create_peer.go
- pkg/bootstrap/platform/config.go
- pkg/bootstrap/platform/k8s.go
- tests/e2e/k8s/util/k8s_yaml.go
Add Namespace to cl-adm to support replacing the namespace for ClusterLink deployment. Add Ingresstype for the operator config.
> pkg/bootstrap: Add ingressType and namespace to config

- design-proposals/crd-based-management.md
> Design for CRD based management

- pkg/bootstrap/platform/k8s.go
This PR removes PVC and peer CA dependencies from CRD-mode yaml.
> bootstrap/platform/k8s: Fix CRD-mode yaml

- cmd/cl-adm/cmd/create/create_peer.go
- cmd/cl-controlplane/app/server.go
- pkg/bootstrap/platform/config.go
- pkg/bootstrap/platform/k8s.go
- pkg/controlplane/instance.go
- pkg/operator/controller/instance_controller.go
- pkg/platform/k8s/platform.go
This PR declares a const for the CL_NAMESPACE env variable. (Note that it was previously called CL-NAMESPACE). The env variable is read once at cmd/cl-controlplane, and propagated downwards.
> cl-controlplane: Changes to namespace env variable

- cmd/cl-dataplane/app/server.go
- pkg/bootstrap/platform/k8s.go
- pkg/controlplane/instance.go
- pkg/operator/controller/instance_controller.go
This PR adds an app name constant for cl-dataplane.
This constant is used by the controlplane to create imported services referencing the dataplane pods.
> cl-dataplane: Add app name constant

- cmd/cl-controlplane/app/server.go
- config/crds/clusterlink.net_imports.yaml
- config/operator/rbac/role.yaml
- pkg/apis/clusterlink.net/v1alpha1/import.go
- pkg/bootstrap/platform/k8s.go
- pkg/controlplane/control/manager.go
- pkg/controlplane/control/port.go
- pkg/operator/controller/instance_controller.go
This PR adds support for updating import target ports.
It also adds support for automatic port allocation in CRD mode.
> controlplane/control: Support port updates

- website/content/en/_index.md
- website/content/en/about/_index.md
- website/content/en/docs/concepts/fabric.md
- website/content/en/docs/concepts/sites.md
- website/content/en/docs/doc-contribution/_index.md
- website/content/en/docs/getting-started/_index.md
- website/content/en/docs/overview/_index.md
Use `{{< ref "page_name#anchor_name" >}}` syntax instead of URL or file system paths for site internal links.
> use hugo ref for linking

- cmd/cl-dataplane/app/envoyconf.go
This PR disables envoy from using TLS session keys when connecting to the controlplane.
Enabling session keys produces big TLS client hello packets, which cause a "buffer full" error on the controlplane's SNI proxy.
> cl-dataplane: Disable controlplane TLS session keys

- cmd/cl-adm/cmd/deploy/deploy_peer.go
- pkg/apis/clusterlink.net/v1alpha1/instance_types.go
- pkg/bootstrap/platform/config.go
- pkg/bootstrap/platform/k8s.go
- pkg/operator/controller/instance_controller.go
Support ingress port flag for the deploy peer command.
> cmd/deploy: Support ingress port flag

- .github/workflows/release.yml
Update the permission to write packages and content for the Release GitHub action.
> .github/workflows: Add write permission to release workflow

- cmd/cl-controlplane/app/server.go
Move peer CRD to be used only in CRD mode.
> cmd/cl-controlplane: Move peer crd to be used only in CRD mode

- cmd/cl-adm/cmd/create/create_peer.go
- cmd/cl-adm/cmd/deploy/deploy_peer.go
- config/crds/clusterlink.net_instances.yaml
- design-proposals/project-deploymnet.md
- pkg/apis/clusterlink.net/v1alpha1/instance_types.go
- pkg/bootstrap/platform/config.go
- pkg/bootstrap/platform/k8s.go
- pkg/operator/controller/instance_controller.go
- pkg/operator/controller/instance_controller_test.go
- tests/e2e/k8s/suite.go
- tests/e2e/k8s/util/k8s_yaml.go
Add a version flag to create and deploy peers to be able to deploy different versions of ClusterLink (not just the latest).
> cl-adm: add version flag to CLI

- tests/e2e/k8s/util/k8s_yaml.go
This PR fixes the function responsible for setting the dataplane debug level.
It was recently broken when introducing the image-tag CLI parameter.
> tests/e2e/k8s: Fix dataplane log-level setting

- website/config.toml
- website/content/en/about/_index.md
- website/content/en/docs/_index.md
... instead of defining the main menu entries in `config.toml`.
Only remaining menu item in the config is GitHub link which does not (and should not) have a corresponding markdown file as it is an external link.
> [website] Move menu items to _index.md front matter

- website/content/en/blog/_index.md
- website/content/en/blog/hello.md
currently set `draft: true` so section and entry are both not rendered.
References #410
> [website] Add blog collection and sample entry

- go.mod
- pkg/controlplane/control/manager.go
This PR changes the system service names to be built using SHA1 (40 hex bytes) instead of SHA256 (64 hex bytes). This is to avoid the DNS name limit of 63 characters.
> controlplane/control: Use shorter system service names

- pkg/controlplane/authz/manager.go
- pkg/policyengine/PolicyDispatcher.go
- pkg/policyengine/connectivitypdp/connection_request.go
- tests/e2e/k8s/test_basic.go
Use policyengine response fields for connection request and add import name to the response
> controlplane/authz: use policyengine response fields for connection request

- .devcontainer/dev/post-create.sh
- hack/install-devtools.sh
Latest gofumpt requires Go 1.21 and we're currently on 1.20.x
> Set gofumpt version to 0.6.0 instead of latest

- website/content/en/docs/getting-started/developers.md
- instructions for rerunning individual tests
- enabling debug level logging in CICD
- labeling PRs to help in changelog generation
Fixes: #153
> Additional documentation for tests and PRs

- pkg/controlplane/control/peer.go
This PR fixes a bug that prevented more than a single update to the peer status.
> controlplane/control: Fix bug in peer status setting

- pkg/controlplane/xds/manager.go
This PR changes Peers Cluster DNS setting to strict, to allow multiple gateways to be used per peer.
> controlplane/xds: Support multiple peer gateways

- pkg/controlplane/control/peer.go
When an unhealthy peer suddently responds to a healthcheck, its monitor immediately switches to using the healthInterval.
This PR makes a fix to switch back to using the unhealthyInterval if the peer returns to not responding to healthchecks.
> controlplane/control: Fix interval while peer is unhealthy

- cmd/clusterlink/cmd/create/create_fabric.go
- cmd/clusterlink/cmd/create/create_peer.go
- cmd/clusterlink/cmd/deploy/deploy_peer.go
- cmd/clusterlink/config/config.go
- demos/utils/common.py
- pkg/bootstrap/cert.go
- tests/e2e/k8s/util/fabric.go
- website/content/en/docs/concepts/fabric.md
- website/content/en/docs/concepts/peers.md
- website/content/en/docs/getting-started/users.md
Add an option to specify the fabric name when creating certificates, by default, will use "default_fabric".
> cmd/clusterlink: Add fabric name to CLI

- pkg/controlplane/authz/controllers.go
- pkg/controlplane/authz/manager.go
Add delete unprivileged policy function,
(Delete privileged policy is still missing -can be done by adding finalizer before deleting to the policies or separate access policy CRDS to privileged and non-privileged)
> policyengine/PolicyDispatcher: allow to delete unprivileged policy

- .github/ISSUE_TEMPLATE/config.yml
- config/crds/clusterlink.net_imports.yaml
- pkg/apis/clusterlink.net/v1alpha1/import.go
- tests/e2e/k8s/test_import.go
- tests/e2e/k8s/util/kind.go
This PR adds an API-server validation for imports to be limited to 63 characters.
This ensures that the respective service name will be valid.
Ref #482
> pkg/apis: Validate import names

- README.md
Remove duplicated text regarding pod-to-pod communications. Splitting the sentence and removing "but".
> Remove duplicated text in README

- config/operator/rbac/role.yaml
- pkg/operator/controller/instance_controller.go
- pkg/operator/controller/instance_controller_test.go
PVC is no longer needed in the CRD mode.
> operator/controller: Remove PVC from the operator.

- Makefile
Small fix to version info in the operator and controlplane images.
Using one "ldfalg" instead of one for each command.
> Makefile: Fix version info flags in docker images

- website/Makefile
- website/config.toml
GitInfo can still be (and is) enabled on local deployments via the `--enableGitInfo` Hugo command line flag.
Fixes #515
> Disable GitInfo on production deployment

- pkg/controlplane/peer/client.go
- tests/e2e/k8s/test_peer.go
This PR changes the client to issue requests in parallel for peers who have multiple gateways.
> controlplane/peer/client: Issue requests in parallel

- cmd/clusterlink/cmd/delete/delete.go
- cmd/clusterlink/cmd/delete/delete_peer.go
- pkg/bootstrap/platform/k8s.go
- website/content/en/docs/getting-started/users.md
Add delete peer command that completely removes ClusterLink from the cluster,
including the operator, CRDs, namespaces, and instances.
> cmd/clusterlink: Introduce delete peer command

- cmd/clusterlink/cmd/create/create_fabric.go
- cmd/clusterlink/cmd/create/create_peer.go
- cmd/clusterlink/cmd/deploy/deploy_peer.go
- cmd/clusterlink/config/config.go
Fix the path flags for the ClusterLink CLI.
> cmd/clusterlink: Fix path flag

- Makefile
- hack/gen-doc-version.sh
- website/config.toml
Automate the creation of a new documentation version.
Process is documented and implemented in `hack/gen-doc-version.sh`
Needs improvement:
- order `param.versions` array correctly (main, new version, previous version, ...) - `sed` seems limited for this and go-toml packages do not handle comments ;-( Maybe awk or perl could be used or maybe we use Go for all (use `os` package o run git, https://github.com/adrg/frontmatter for frontmatter, etc.) and clean up comments from the file?
- add (git) release version to script parameters so it can be auto updated as well?
- auto update the `docs/${NEW_DOCS_VERSION}/_index,md` file's frontmatter
Fixes #531
> Automation script to generate new docs version

- .licenserc.yaml
- website/config.toml
- website/layouts/index.redirects
add automatic generation of netlify formatted _redirects file.
- introduce rules for redirecting `/docs` to `/docs/<latest>` and `/docs/*` to `/docs/latest/*`. 
- set latest based on `last_stable_version` in config.toml
More rules can be added to `layouts/index.redirect`. See issue #532 for more context.
Fixes #532
> [website]: add netlify _redirects file

- website/config.toml
Fixes #463.
- Enable google analytics
- Enable feedback events (e.g., to prioritize page views with low useful score)
> [website] Docs/google analytics

- website/content/en/blog/hello-world/index.md
- website/content/en/docs/main/concepts/fabric.md
- website/content/en/docs/main/concepts/peers.md
- website/content/en/docs/main/concepts/policies.md
- website/content/en/docs/main/concepts/services.md
- website/content/en/docs/main/doc-contribution/_index.md
- website/content/en/docs/main/getting-started/_index.md
- website/content/en/docs/main/getting-started/developers.md
- website/content/en/docs/main/getting-started/users.md
- website/content/en/docs/main/overview/_index.md
- website/content/en/docs/main/tasks/operator.md
- website/content/en/docs/main/tutorials/bookinfo/index.md
- website/content/en/docs/main/tutorials/iperf/index.md
Fixes #527
Using named links on `main` docs and *not* applying to already released documentation versions.
> [website] use default named links

- cmd/clusterlink/cmd/create/create_peer.go
- cmd/clusterlink/cmd/deploy/deploy_peer.go
- pkg/bootstrap/cert.go
- pkg/bootstrap/crypt.go
This PR fixes the clusterlink deploy peer command which unnecessarily required reading the fabric and peer private keys.
Fixes #565
> clusterlink deploy peer: Remove CA private keys requirement

- .github/workflows/release.yml
- Makefile
- cmd/cl-controlplane/Dockerfile
- cmd/cl-dataplane/Dockerfile
- cmd/cl-go-dataplane/Dockerfile
- cmd/cl-operator/Dockerfile
- demos/iperf3/cloud/test.py
- demos/iperf3/testdata/manifests/iperf3-client/iperf3-client.yaml
- demos/iperf3/testdata/manifests/iperf3-client/iperf3-client2.yaml
- demos/iperf3/testdata/manifests/iperf3-server/iperf3.yaml
- demos/utils/cloud.py
Create support for arm64 architecture for docker images:
1) Update the GitHub action.
2) Update the makefile to compile images according to the architecture
3) Update the docker file to use the correct binary file.
4) Update the push image command to use the --platform flag for multi-architecture Docker image compilation.
5) Update the iperf3 demo to support arm64 architecture.
> Create support for arm64 architecture for docker images.

- netlify.toml
Fixes #554 
The files are not really duplicates - netlify expects the configuration in the repo's toplevel directory. 
This is only a pointer to the actual site which is under the base directory.
> [website] clean and document toplevel netlify config

- tests/e2e/k8s/test_basic.go
This PR fixes a race where a peer status is updated after being fetched for comparison.
> tests/e2e/k8s: Fix race in peer status check

- .github/workflows/linkcheck.yml
Add jobs.<job_name>.if condition based on `owner` (could have used `github.repository` as well).
Syntax is documented in https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution
> Update linkcheck.yml to only run on main repo and not on forks

- pkg/controlplane/api/authz.go
- pkg/controlplane/authz/manager.go
- pkg/controlplane/authz/server.go
> Send attributes of source workload to remote peer

- cmd/clusterlink/cmd/create/create_peer.go
- cmd/clusterlink/cmd/deploy/deploy_peer.go
- website/content/en/docs/main/tasks/operator.md
Create the ClusterLink components' certificates on the `deploy peer`  instead of in the `create peer-cert` command.
> CLI: Enhancement for creation of ClusterLink components' certificates

- cmd/cl-controlplane/app/server.go
- go.mod
- pkg/controlplane/authz/manager.go
- pkg/controlplane/control/peer.go
- pkg/controlplane/peer/certs.go
- pkg/controlplane/xds/manager.go
- pkg/dataplane/client/xds.go
- pkg/util/runnable/manager.go
- tests/e2e/k8s/test_dynamic.go
- tests/e2e/k8s/util/clusterlink.go
This PR changes the controlplane to watch the peer certificate files for changes, in order to support dynamic peer certificates.
Note that when switching TLS certificates, existing connections are still valid.
The client-side controlplane (the importer) terminates those controlplane connections when switching certificates.
However, if only the server switches certificates, the server will continue to allow authz connections, which will be dropped only at the tunnel establishment phase (where a new connection is used).
> cmd/cl-controlplane: Support dynamic peer certificates

- pkg/controlplane/api/servername.go
Update the controlplane port to be higher than 1024 (below does not allow for non-root users in OpenShift clusters).
> controlplane: Change listen port number

- cmd/cl-controlplane/app/server.go
- cmd/cl-dataplane/app/envoyconf.go
- cmd/cl-dataplane/app/server.go
- cmd/cl-go-dataplane/app/server.go
- pkg/dataplane/api/servername.go
Fix the key path and listening port for datapalne to support Openshift.
> dataplane: Fix certificate path and listening port

- pkg/bootstrap/platform/k8s.go
Add zero bytes to empty certificates that are used for cleanup by ClusterLink CLI.
> CLI: Add zero bytes to empty certificates

- website/config.toml
Change config to enable last modification time in frontmatter based on available metadata.
The use of GitInfo is synchronized with netlify.toml setting (previously disabled on local builds and enabled on netlify only)
> [website] enable and use git info for lastmod time

- website/content/en/docs/main/tutorials/iperf/index.md
- website/content/en/docs/main/tutorials/nginx/index.md
- website/content/en/docs/v0.3/tutorials/iperf/index.md
- website/content/en/docs/v0.3/tutorials/nginx/index.md
- website/static/files/tutorials/allow-all-policy.md
`readfile` function is not able to support `tabpane` for more than one file, so I  remove the `tabpane` from the included file
> website: Fix allow-all-policy.md

- .golangci.yaml
- pkg/controlplane/control/manager.go
Fix format warnings: 
WARN [config_reader] The configuration option `output.format` is deprecated, please use `output.formats`
> golangci: Fix format warning

- .github/workflows/pr-cli.yml
- tests/cli/basic_test.sh
Add installation check using the CLI :
This test checks the CLI commands for creating certificates, deploying peers, and deleting them.
> .github/workflows: Add CLI installation checks.

- cmd/clusterlink/cmd/deploy/deploy_peer.go
- pkg/bootstrap/platform/config.go
- pkg/bootstrap/platform/k8s.go
- tests/e2e/k8s/suite.go
- tests/e2e/k8s/test_operator.go
- tests/e2e/k8s/test_redundancy.go
- tests/e2e/k8s/util/fabric.go
- tests/e2e/k8s/util/k8s_yaml.go
This PR adds an option for deploying clusterlink with multiple controlplane replicas.
> Support multiple controlplane replicas

- cmd/cl-controlplane/app/server.go
- cmd/cl-dataplane/app/envoy.go
- cmd/cl-dataplane/app/envoyconf.go
- cmd/cl-dataplane/app/server.go
- cmd/cl-go-dataplane/app/server.go
- pkg/bootstrap/cert.go
- pkg/bootstrap/platform/k8s.go
- pkg/controlplane/api/const.go
- pkg/controlplane/authz/manager.go
- pkg/controlplane/control/manager.go
- pkg/dataplane/api/const.go
- pkg/dataplane/client/fetcher.go
- pkg/dataplane/client/xds.go
- pkg/dataplane/server/server.go
- pkg/operator/controller/instance_controller.go
- pkg/operator/controller/instance_controller_test.go
- pkg/util/http/server.go
- tests/e2e/k8s/suite.go
- tests/e2e/k8s/test_operator.go
- tests/e2e/k8s/util/clusterlink.go
- tests/e2e/k8s/util/fabric.go
- tests/e2e/k8s/util/k8s_yaml.go
This PR adds container readiness probes to the controlplane and dataplane (both go and envoy) containers.
> Add container readiness probes

- config/crds/clusterlink.net_instances.yaml
- pkg/apis/clusterlink.net/v1alpha1/instance_types.go
- pkg/operator/controller/instance_controller_test.go
This PR changes the Instance CRD to support
an empty container registry (i.e. a local registry). The clusterlink CLI will still use the default gchr.io/clusterlink-net registry.
> Instance CRD: Support empty registry

- pkg/controlplane/api/authz.go
- pkg/controlplane/authz/manager.go
- pkg/controlplane/control/manager.go
This PR switched the JWT algorithm from RS256 to HS256.
> controlplane/authz: Use a faster JWT algorithm

- pkg/dataplane/server/dataplane.go
- pkg/util/tls/util.go
This PR adds a TLS session cache used by controlplane and go-dataplane TLS clients.
> Cache TLS sessions

- website/content/en/docs/main/tasks/relay/index.md
- website/content/en/docs/v0.4/tasks/relay/index.md
Fix notify note to have the correct background as all in website. both in main and v0.4
Currently note looks like the following:
Changed to looks like the following:
> fix notify note to look as the rest of the notes

- pkg/controlplane/control/manager.go
- pkg/controlplane/control/port.go
- tests/e2e/k8s/suite.go
- tests/e2e/k8s/util/k8s_yaml.go
> fix linter errors on existing files
